"""Final Analytics Epilogue: Is the Game Balanced?

Back in Level 1 you first analyzed combat data with NumPy and Pandas on a
small, early version of this game. The Data Recall Checkpoint (after Level
3) brought those skills back once more, on the validated combat log. The
RPG has since grown a CLI, a quality-gated test suite, an HTTP API, and
concurrent/background tournament running (Levels 4-7). Now it's time to
close the loop: use NumPy and Pandas a third time, on data generated by the
system you actually built, to answer the question this whole course started
with — is the game balanced?

See README.md for the full brief, a short recall cheat-sheet, and the
analytical questions this epilogue asks you to answer.

Check: uv run python check.py
"""
from pathlib import Path

import numpy as np
import pandas as pd

DATA_DIR = Path(__file__).parent / "data"


# ── NumPy: one battle matchup, many battles ─────────────────────────────────

def load_battle_arrays(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load a deep-dive battle log into three parallel NumPy arrays.

    The JSON file has a top-level "battles" list; each entry has "winner"
    ("hero" or "monster"), "rounds" (int), and "gold_earned" (int).

    TODO:
    - read and parse the JSON at `path`
    - build three NumPy arrays of shape (N,), all in the same battle order:
      - wins: 1 where winner == "hero", else 0
      - rounds: the rounds value of each battle
      - gold: the gold_earned value of each battle
    - return (wins, rounds, gold)
    """
    raise NotImplementedError


def deep_dive_stats(wins: np.ndarray, rounds: np.ndarray) -> dict[str, float | int]:
    """NumPy statistics over one matchup's battles.

    A "quick hero win" is a battle the hero won in 2 rounds or fewer —
    computing it needs a boolean mask on `wins` combined (`&`) with a
    boolean mask on `rounds`, not two separate counts added together.

    Return a dict with exactly these keys:
    - "hero_win_rate": fraction of battles the hero won
    - "median_rounds": median of `rounds`
    - "rounds_std": population standard deviation of `rounds`
    - "rounds_p90": 90th percentile of `rounds` (linear interpolation)
    - "quick_hero_wins": count of battles where the hero won AND rounds <= 2

    TODO:
    - compute hero_win_rate as a NumPy mean reduction over `wins`
    - compute median_rounds, rounds_std, rounds_p90 with NumPy
    - build a combined boolean mask (hero won AND rounds <= 2) and count it
    - return the five values in a dict
    """
    raise NotImplementedError


def battle_matrix_summary(wins: np.ndarray, rounds: np.ndarray) -> dict[str, float]:
    """Recall 2D arrays and axis-based aggregation (Level 1 Mission 19).

    Stack `wins` and `rounds` into one (N, 2) matrix — column 0 is wins,
    column 1 is rounds — and reduce along axis=0 to get one mean per
    column, rather than computing the two means separately.

    Return {"mean_win_indicator": ..., "mean_rounds": ...}.

    TODO:
    - build an (N, 2) matrix from wins and rounds
    - reduce it along axis=0 to get a mean per column
    - return the two resulting means in a dict
    """
    raise NotImplementedError


# ── Pandas: tournament history across many matchups ────────────────────────

def load_tournament_history(path: Path) -> pd.DataFrame:
    """Load the tournament history CSV into a DataFrame.

    TODO:
    - read the CSV at `path` with pandas
    - return the resulting DataFrame
    """
    raise NotImplementedError


def win_rate_by_class(df: pd.DataFrame) -> dict[str, float]:
    """Average hero win rate per hero_class, across all of that class's runs.

    Each row is already one run's hero_win_rate (not raw battles) — group
    by hero_class and average that column.

    TODO:
    - group by hero_class using pandas' groupby
    - average the hero_win_rate column per group
    - return the per-class averages as a plain dict
    """
    raise NotImplementedError


def rank_monsters(df: pd.DataFrame) -> list[str]:
    """Rank monsters from hardest to easiest by average hero win rate.

    "Difficulty" here is only this one operational metric — the monster
    with the LOWEST average hero_win_rate across all runs is hardest. Not a
    universal definition, just what this exercise measures.

    TODO:
    - group by monster, average hero_win_rate per group
    - sort ascending (lowest win rate = hardest, first)
    - return the monster names as a list, in that order
    """
    raise NotImplementedError


def unfavorable_matchups(df: pd.DataFrame) -> list[str]:
    """Matchups where the hero's average win rate is below 0.5, worst first.

    TODO:
    - group by matchup, average hero_win_rate per group
    - keep only groups with average win rate < 0.5
    - sort ascending (lowest win rate = worst for the hero, first)
    - return the matchup names as a list, in that order
    """
    raise NotImplementedError


def balance_conclusions(df: pd.DataFrame) -> dict[str, str | int]:
    """Three headline conclusions about the tournament history in `df`.

    Return a dict with exactly these keys:
    - "hardest_monster": monster with the lowest average hero_win_rate
    - "longest_matchup": matchup with the highest average avg_rounds —
      this measures fight LENGTH, not difficulty; don't conflate the two
    - "one_sided_matchup_count": how many matchups in `df` have an average
      hero_win_rate of exactly 0.0 or exactly 1.0 (a completely one-sided
      matchup, in either direction)

    These must work on `df` as given — not assume it's the full 9-matchup
    history. A caller may pass a smaller slice (e.g. only a few matchups);
    "hardest_monster" and "longest_matchup" are about whichever monsters/
    matchups are actually present in `df`, and "one_sided_matchup_count"
    is a count within `df`, not a fixed global number.

    No correlation or inferential statistics — these are plain groupby
    aggregations.

    TODO:
    - group by monster, average hero_win_rate per group → hardest_monster
    - group by matchup, average avg_rounds per group → longest_matchup
    - group by matchup, average hero_win_rate per group, count how many
      groups equal 0.0 or 1.0 → one_sided_matchup_count
    - return the three answers in a dict
    """
    raise NotImplementedError


# ── Final synthesis ──────────────────────────────────────────────────────

def build_final_report(deep_dive_path: Path, history_path: Path) -> dict[str, object]:
    """Combine the NumPy deep-dive and Pandas tournament-history results.

    Call the functions above rather than recomputing anything by hand.

    Return a dict with exactly these keys:
    - "deep_dive": the deep_dive_stats() dict
    - "matrix_summary": the battle_matrix_summary() dict
    - "win_rate_by_class": the win_rate_by_class() dict — mean win rate
      observed in this recorded history, not a claim about inherent class
      balance (five runs per matchup is a small sample)
    - "monster_ranking": the rank_monsters() list
    - "unfavorable_matchups": the unfavorable_matchups() list
    - "conclusions": the balance_conclusions() dict

    TODO:
    - load the deep-dive arrays and compute deep_dive_stats + battle_matrix_summary
    - load the tournament history and compute the four Pandas results
    - assemble and return the combined dict
    """
    raise NotImplementedError


if __name__ == "__main__":
    report = build_final_report(
        DATA_DIR / "deep_dive_battles.json",
        DATA_DIR / "tournament_history.csv",
    )
    import json
    print(json.dumps(report, indent=2))
